export const response = {
  plan: [
    { d: "11/03", s: "Maths", t: "Ratio" },
    { d: "11/03", s: "Maths", t: "Angles" },
    { d: "12/03", s: "Maths", t: "Vectors" },
    { d: "12/03", s: "Maths", t: "Brackets" },
    { d: "13/03", s: "Maths", t: "Measures" },
    { d: "13/03", s: "Maths", t: "Sequences" },
    { d: "14/03", s: "Maths", t: "Box plots" },
    { d: "14/03", s: "Maths", t: "Pie charts" },
    { d: "15/03", s: "Maths", t: "Standard form" },
    { d: "15/03", s: "Maths", t: "Scale diagrams" },
    { d: "16/03", s: "Maths", t: "Transformations" },
    { d: "16/03", s: "Maths", t: "Roots and powers" },
    { d: "16/03", s: "Maths", t: "Compound measures" },
    { d: "16/03", s: "Maths", t: "Volume" },
    { d: "16/03", s: "Maths", t: "Operations" },
    { d: "16/03", s: "Maths", t: "Proportion" },
    { d: "17/03", s: "Maths", t: "Histograms" },
    { d: "17/03", s: "Maths", t: "Index rules" },
    { d: "17/03", s: "Maths", t: "Place value" },
    { d: "17/03", s: "Maths", t: "Inequalities" },
    { d: "17/03", s: "Maths", t: "Surface area" },
    { d: "17/03", s: "Maths", t: "Number skills" },
  ],
};
