import Image from "next/image";
import { Button, Link, Stack, Container } from "@mui/material";
import { ThemeRegistry } from "./components/ThemeRegistry/index";
import Colors from "@mytutor/mytutor-design-system/styles/tokens/colors";
import "./styles/globals.css";
import "./styles/fonts.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        style={{
          backgroundColor: Colors.sand[30],
          maxWidth: "592px",
          margin: "auto",
          padding: "16px",
        }}
      >
        <ThemeRegistry>
          <Container maxWidth="xs" margin="auto">
            <Stack
              component="header"
              direction="row"
              gap={2}
              justifyContent="space-between"
              alignItems="center"
              sx={{
                marginBottom: "16px",
                py: 2,
                zIndex: 2,
              }}
            >
              <Button color="secondary">Menu</Button>
              <Link href="/">
                <Image
                  src={`/logo.svg`}
                  alt="MyTutor"
                  width={100}
                  height={36}
                />
              </Link>
            </Stack>
            {children}
          </Container>
        </ThemeRegistry>
      </body>
    </html>
  );
}
