import { ThemeRegistry } from "./components/ThemeRegistry/index";
import Colors from "@mytutor/mytutor-design-system/styles/tokens/colors";
import './styles/globals.css';
import './styles/fonts.css';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        style={{
          backgroundColor: Colors.sand[30]
        }}
      >
      <ThemeRegistry>
        {children}
      </ThemeRegistry>
      </body>
    </html>
  )
}
